# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:            pretty
#relative_permalinks:  true

# Dependencies
markdown:             kramdown
highlighter:          pygments

# Setup
title:                resir014
tagline:              I make things.
url:                  https://resir014.github.io
baseurl:              ""
exclude:              ["Makefile", "Gruntfile.js", "Gemfile", "README.md", "LICENSE", "node_modules", "package.json"]

# Disqus comments
disqus_shortname:     resir014

# Gems
gems:
  - octopress-paginate
  - jekyll-gist

# octopress-paginate
pagination:
  limit:              false
  per_page:           1
  permalink:          /page/:num/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:           _sass
  style:              :compressed

# List of time zones supported in the TZ database
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:             Asia/Jakarta

# About/contact
author:
  name:               Resi Respati
  url:                https://twitter.com/resir014
  email:              resir014@gmail.com

# Custom vars
version:              2.1.2
github:
  repo:               https://github.com/resir014/resir014.github.io

# Navigational menus
nav:
  - title: blog
    url: /blog
  - title: about
    url: /about
  - title: projects
    url: /projects

# Collections
collections:
  stuff:
    output:           true
    permalink:        /:path/
  webdesign:
    output:           true
    permalink:        /projects/:collection/:path/
  blogs:
    output:           true
    permalink:        /projects/:collection/:path/
  github:
    output:           true
    permalink:        /projects/:collection/:path/
