# Permalinks
permalink:           pretty

# Setup
title:               "@resir014"
tagline:             "Thoughts on life."
description:         "Writings, ramblings, and projects of Resi Respati (@resir014)."
url:                 https://resir014.github.io
baseurl:             ""
paginate:            5
paginate_path:       "/page/:num/"

# Exclude these files from Jekyll build
exclude:
  - "Makefile"
  - "Gruntfile.js"
  - "Gemfile"
  - "README.md"
  - "LICENSE"
  - "node_modules"
  - "bower_components"
  - "package.json"
  - "bower.json"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:             :compressed

# List of time zones supported in the TZ database
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:            Asia/Jakarta

# About/contact
author:
  name:              Resi Respati
  url:               https://twitter.com/resir014
  email:             resir014@gmail.com

# Disqus comments
disqus_shortname:    resir014

# Gems
gems:
  - jekyll-gist
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

# Navigational menus
nav:
  - title: about
    url: /about
  - title: projects
    url: /projects
  - title: music
    url: /music
  - title: stuff
    url: /etc

# Collections
collections:
  stuff:
    output:           true
    permalink:        /:path/
  projects:
    output:           true
    permalink:        /:collection/:path/
  etc:
    output:           true
    permalink:        /:collection/:path/
