# Permalinks
permalink:          pretty

# Exclude these files from Jekyll build
exclude:
  - "Makefile"
  - "Gruntfile.js"
  - "Gemfile"
  - "README.md"
  - "LICENSE"
  - "node_modules"
  - "bower_components"
  - "package.json"
  - "bower.json"

# Gems
gems:
  - jekyll-redirect-from

# Collections
collections:
  stuff:
    output: true
    permalink: /:path/
  projects:
    output: true
    permalink: /:collection/:path/
  etc:
    output: true
    permalink: /:collection/:path/
