# Permalinks
permalink:            pretty

# Dependencies
markdown:             kramdown
highlighter:          rouge

# Setup
title:                double-slash
tagline:              "writings, ramblings, and projects of @resir014"
url:                  https://resir014.github.io
baseurl:              ""
exclude:              ["Makefile", "Gruntfile.js", "Gemfile", "README.md", "LICENSE", "node_modules", "bower_components" "package.json", "bower.json"]

# Disqus comments
disqus_shortname:     resir014

# Jekyll plugins
gems:
  - jekyll-gist
  - jekyll-sitemap
  - octopress-paginate

# Don't automatically trigger page build on GitHub
include:
  - .nojekyll

# Plugin: octopress-paginate
pagination:
  limit:              false
  per_page:           1
  permalink:          /page/:num/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:           _sass
  style:              :compressed

# List of time zones supported in the TZ database
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:             Asia/Jakarta

# About/contact
author:
  name:               Resi Respati
  url:                https://twitter.com/resir014
  email:              resir014@gmail.com

# Navigational menus
nav:
  - title: about
    url: /about
  - title: projects
    url: /projects
  - title: blog
    url: /blog

# Collections
collections:
  stuff:
    output:           true
    permalink:        /:path/
  projects:
    output:           true
    permalink:        /:collection/:path/
