# Permalinks
permalink:           pretty

# Setup
title:               double-slash
tagline:             "writings, ramblings, and projects of @resir014"
url:                 https://resir014.github.io
baseurl:             ""
exclude:              ["Makefile", "Gruntfile.js", "Gemfile", "README.md", "LICENSE", "node_modules", "bower_components", "package.json", "bower.json"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# List of time zones supported in the TZ database
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:             Asia/Jakarta

# About/contact
author:
  name:              Resi Respati
  url:               https://twitter.com/resir014
  email:             resir014@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Don't automatically trigger page build on GitHub
include:
  - .nojekyll

# Gems
gems:
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
  - octopress-paginate

# Plugin: octopress-paginate
pagination:
  limit:              false
  per_page:           1
  permalink:          /page/:num/

# Navigational menus
nav:
  - title: about
    url: /about
  - title: projects
    url: /projects
  - title: music
    url: /music
  - title: stuff
    url: /etc

# Collections
collections:
  stuff:
    output:           true
    permalink:        /:path/
  projects:
    output:           true
    permalink:        /:collection/:path/
  music:
    output:           true
    permalink:        /:collection/:path/ #can be overriden in the file
  etc:
    output:           true
    permalink:        /:collection/:path/ #can be overriden in the file
